CREATE DATABASE CONVERSOR
CREATE TABLE Transacoes(
						Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
						TRNTYPE VARCHAR(10),
						DTPOSTED  VARCHAR(20),
						TRNAMT DECIMAL,
						FITID INT,
						CHECKNUM INT,
						NAME VARCHAR(40),
						MEMO VARCHAR(50))
select * from Transacoes




